[options]
db_host = postgres
db_port = 5432
db_user = odoo
db_password = odoo
db_name = idata_dev

addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/backend
admin_passwd = admin

without_demo = all
proxy_mode = False
log_level = info
logfile = /var/log/odoo/odoo.log
workers = 0
max_cron_threads = 1

